artifact_uri: /Users/evanlee/Desktop/AcneDetection/part1_detection/runs/mlflow/992686724991543153/3c6ea84008cd4a4ea1478fa1174714f8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '992686724991543153'
lifecycle_stage: active
run_id: 3c6ea84008cd4a4ea1478fa1174714f8
run_name: acne04
source_name: ''
source_type: 4
source_version: ''
start_time: 1778109644195
status: 1
tags: []
user_id: evanlee
